# Generated by Django 5.2.8 on 2025-11-28 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("executions", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "prompt",
                    models.TextField(
                        help_text="System prompt template. Supports variables: %SETTINGS%, %AGENTS%, %PAGES%, etc."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agent role identifier (e.g., 'brainstorm', 'summary', 'host')",
                        max_length=100,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="llama3.1:8b",
                        help_text="Default LLM model to use",
                        max_length=100,
                    ),
                ),
                ("default_temperature", models.FloatField(default=0.7)),
                ("default_max_tokens", models.IntegerField(default=512)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voice sample for TTS output",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rules",
                    models.TextField(
                        help_text="Game rules and instructions for the orchestration"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Default variables for sessions (e.g., topic, depth)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        blank=True,
                        help_text="Generated workflow template for this game",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_template",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Associated URL if content is about a web page",
                        max_length=2000,
                    ),
                ),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcripts",
                        to="workflows.agent",
                    ),
                ),
                (
                    "audio_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated audio file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcripts",
                        to="assets.asset",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="executions.execution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("turn_order", models.PositiveIntegerField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_roles",
                        to="workflows.agent",
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override voice for this role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.asset",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="workflows.gametemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_order"],
                "unique_together": {("game", "turn_order")},
            },
        ),
        migrations.CreateModel(
            name="WebPage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                (
                    "url_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of URL for fast lookups",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "parent_url_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Hash of parent URL (the page this was linked from)",
                        max_length=64,
                    ),
                ),
                (
                    "search_term",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("search_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("last_loaded", models.DateTimeField(blank=True, null=True)),
                ("last_opened", models.DateTimeField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="executions.execution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["execution", "parent_url_hash"],
                        name="workflows_w_executi_529915_idx",
                    ),
                    models.Index(
                        fields=["execution", "search_term"],
                        name="workflows_w_executi_a9763a_idx",
                    ),
                ],
                "unique_together": {("execution", "url_hash")},
            },
        ),
    ]
